server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  loggers:
    io.cratekube: DEBUG
    org.reflections: ERROR

provider: ${CLOUD_PROVIDER:-aws}

swagger:
  resourcePackage: io.cratekube.cloud.resources
