server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  loggers:
    io.cratekube: DEBUG
    org.reflections: ERROR

service:
  provider: ${CLOUD_PROVIDER:-aws}
  configDir: ${CONFIG_DIR:-/app/config}

auth:
  api-keys:
  - name: api-admin
    key: ${ADMIN_APIKEY:-}
    roles: ['admin']

swagger:
  resourcePackage: io.cratekube.cloud.resources
